language: node_js
node_js:
  - "14"
branches:
  only:
    - master
install:
  - npm ci
script:
  - NODE_ENV=test npm run-script test-travis
after_success:
  - |
    if ([ "$TRAVIS_BRANCH" == "master" ] || [ ! -z "$TRAVIS_TAG" ]) && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
      git config --global user.email "travis@travis-ci.org"
      git config --global user.name "Travis CI"
      git remote set-url --push origin "https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git"
      git remote -v
      git checkout -f -b version-branch
      npm version patch -m "$(git log -1 --pretty=%B) .... bump version [skip ci]"
      git push origin version-branch:master --follow-tags
      npm run build
    else
      echo "version skiped!"
    fi
deploy:
  - provider: releases
    api_key: "$GH_TOKEN"
    file:
      - "output/hkubectl-linux"
      - "output/hkubectl-macos"
      - "output/hkubectl-win.exe"
    skip_cleanup: true