# This is a basic workflow to help you get started with Actions

name: CI-PR

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch.
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test_and_build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - run: npm ci
      - run: NODE_ENV=test npm run-script test-travis
      - run: npm run build
      - name: Checksum
        working-directory: ./output/
        run: |
          sha256sum * > checksums.txt
          sha256sum *
      - uses: actions/upload-artifact@v3
        with:
          name: output
          path: ./output/
      - name: Trigger Update Files in kube-HPC.github.io
        run: |
          curl -X POST https://api.github.com/repos/kube-HPC/kube-HPC.github.io/dispatches \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -d '{"event_type": "hkubectl-release"}'